### ISSUE TITLE
Alignment misunderstanding

### ISSUE THREAD

**Issue by lauti7** [jonhoo/rust-for-rustaceans.com#34]
chapter: 2
page: 20
kind: text
reporter: @lauti7
date: 2023-13-03

On page 20, when you talk about type Alignment, what do you mean by saying: "You can create a pointer only to byte 0 or byte 1 (bit 8)"? I mean I understand that it refers to the address of the type (value) but why "byte 0 or **byte 1 (bit 8)**"?

**Comment by jonhoo** [comment]
I mean that you can't, for example, make a pointer to bit 4 for example :)
