### ISSUE TITLE
Possible superfluous `&*`: print02-ch02-lst03

### ISSUE THREAD

**Issue by BatmanAoD** [jonhoo/rust-for-rustaceans.com#39]
Not submitting this as an errata just yet because it could be my misunderstanding.

Listings 2-2 and 2-3 contrast static vs dynamic dispatch.

2-2:
```rust
impl String {
    pub fn contains(&self, p: impl Pattern) -> bool {
        p.is_contained_in(self)
    }
}
```

2-3:
```rust
impl String {
    pub fn contains(&self, p: &dyn Pattern) -> bool {
        p.is_contained_in(&*self)
    }
}
```

I was curious what the purpose of `&*` in listing 2-3 was, especially since it's not present in listing 2-2 and I don't know why the explicit dereference would be necessary for dynamic but not for static dispatch (especially the dispatch isn't happening on `self` but on `p`). I wrote up 2-3 [in the Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=121153a798e90f33bd661db58944ec99), _without_ the `&*` (and also modified to not conflict with the standard library types), and it compiled, so it seems like in fact it's not necessary.

I did notice that the string argument for `Pattern::is_contained_in` is `&str`, so there does need to be a Deref conversion, but `&self` should already do this, whether or not `is_contained_in` is dynamically or statically dispatched.

Even if this particular example doesn't need `&*`, is there a situation in which switching some value from an `impl` to a `dyn` type would require introducing `&*`?

**Comment by jonhoo** [comment]
Hmm, no, I think you're entirely right that the `&*` isn't needed here!

There _are_ cases where `&*` are needed, but not specifically for dynamic dispatch as far as I'm aware :+1:

**Comment by BatmanAoD** [comment]
Is there anything in the book about when to use `&*`? It's usually just to force a `Deref` impl to kick in, right?

I'll open an errata PR.

**Comment by jonhoo** [comment]
Yep, forcing `Deref` is generally what you're going for with this pattern.
