### ISSUE TITLE
Full representation of `str` should describe length

### ISSUE THREAD

**Issue by cphoenix-google** [jonhoo/rust-for-rustaceans.com#47]
On p. 2, 

Similarly, the
str "Hello world" is a value in the domain of all strings whose representation
is its UTF-8 encoding.

The representation of a C string includes its closing \0. The sequence of UTF-8 bytes of a `str` has an implicit length, which must somehow be explicit in its actual in-memory representation. When discussing the byte representation of a `str` value, I'd like to know explicitly how the length is represented, or at least a mention "The length of the bytes is also stored as  described in section..."

**Comment by cphoenix-google** [comment]
It could also be useful to know whether the length bytes and the UTF-8 bytes are adjacent, or can be in separated locations in memory, or even different types of memory (e.g. heap and stack)

**Comment by cphoenix-google** [comment]
...Now I see the sidebar on page 3. But reading the book linearly, I didn't see it till after I was thrown by the assertion that a `str` is nothing but the UTF-8 sequence-in-memory of its bytes.

**Comment by jonhoo** [comment]
I appreciate the feedback, but for the section that talks about _values_ (as distinct from places), I'd like to avoid also getting into the representation of the pointers _to_ such values.
